Repository dokidzung/32BitJam, pull requests merged in 2021-09, with the labels that each got.

#13 Renamed Tamogachi related things to Tomobachi.
  Assets/Materials/Tomobachi.meta
  Assets/Prefabs/Tomobachi.meta
  Assets/Scenes/Tomobachi.meta
  Assets/Scripts/Tomobachi.meta
Labels: bug, TDE, DBE, TBE

#26 Renaming things 'cause I got it wrong the first time.
  Assets/Materials/Tomobachi.meta
  Assets/Prefabs/Tomobachi.meta
  Assets/Scenes/Tomobachi.meta
  Assets/Scripts/Tomobachi.meta
Labels: bug, TDE, DBE, TBE

#10 #6: Added rudimentary player movement.
  Assets/Materials/Utility/DevFloor.mat
  Assets/Scenes/TopDownSpecific/TopDownSandbox.unity
  Assets/Scripts/Utility/SetBottomMeshToZero.cs
  Assets/Scripts/Utility/WasdMovement.cs
  Assets/Scripts/Utility/WasdMovement.cs.meta
Labels: feature, TDE

#27 #7: TDE sample map
  Assets/Materials/Utility/Blue.mat
  Assets/Materials/Utility/Blue.mat.meta
  Assets/Scenes/TopDownSpecific/TopDownSandbox.unity
  Assets/Scripts/Utility/SetBottomMeshToZero.cs
Labels: feature, TDE

#34 Issue/tde#5 #29 papa johns
  .gitignore
  .vs/32BitJam/v16/Server/sqlite3/storage.ide
  .vs/32BitJam/v16/Server/sqlite3/storage.ide-shm
  .vs/32BitJam/v16/Server/sqlite3/storage.ide-wal
  Assets/Materials/Utility/Materials.meta
  Assets/Materials/Utility/Materials/templategrid_albedo.mat
  Assets/Materials/Utility/Materials/templategrid_albedo.mat.meta
  Assets/Materials/Utility/templategrid_albedo.png
  Assets/Materials/Utility/templategrid_albedo.png.meta
  Assets/Prefabs/Utility/Dash Particle.prefab
  Assets/Prefabs/Utility/Dash Particle.prefab.meta
  Assets/Scenes/TopDownSpecific/TopDownSandbox.unity
  Assets/Scripts/Utility/ControllerMovement.cs
  Assets/Scripts/Utility/ControllerMovement.cs.meta
  Assets/Scripts/Utility/SmoothCamera.cs
  Assets/Scripts/Utility/SmoothCamera.cs.meta
  Assets/Scripts/Utility/WasdMovement.cs
  ProjectSettings/InputManager.asset
Labels: feature, TDE

#42 TDE: Mouse look
  Assets/Scenes/TopDownSpecific/TopDownSandbox.unity
  Assets/Scripts/Utility/MouseLook.cs
  Assets/Scripts/Utility/MouseLook.cs.meta
  Assets/Scripts/Utility/SetBottomMeshToZero.cs
  Assets/Scripts/Utility/SimpleCamera.cs
  Assets/Scripts/Utility/SimpleCamera.cs.meta
Labels: feature, TDE

#45 Downsample
  Assets/Scenes/TopDown/TopDownSandbox.unity
  Assets/Scripts/Utility/DownsampleCamera.cs
  Assets/Scripts/Utility/DownsampleCamera.cs.meta
  Assets/Scripts/Utility/DownsampleController.cs
  Assets/Scripts/Utility/DownsampleController.cs.meta
Labels: feature, TDE, DBE, TBE
